Translations (v1.0.4)
SampleText2k77/nr-local-bel pull request #12
Opened 2023-05-23 17:22 UTC by SampleText2k77

2023-05-23 17:23 UTC, SampleText2k77 commented on game.po
> +# Перакладзена больш вольна, каб было аднолькава с аналагічным апісаннем для максімальнага тармажэння цягніка.
`з аналагічным`

2023-05-23 17:27 UTC, SampleText2k77 commented on game.po
> +msgstr "Даныя гэтага мода ўключаны ў бягучай гульні, але ўсталёваныя файлы патрабуюць навейшую версію гульні. Абнавіце гульню."
`усталяваныя`?

2023-05-24 07:55 UTC, RedRibbon297 commented on game.po
> +msgstr "Верхняя мяжа цягавага намагання цягніка. Фактычнае намаганне можа быць меншым у залежнасці ад магчымасцяў цягніка."
"... можа быць менш... "
Если по русски: "фактическое усилие может быть меньше в зависимости от ..."

2023-05-24 08:02 UTC, RedRibbon297 commented on game.po
> +msgstr "Верхняя мяжа цягавага намагання цягніка. Фактычнае намаганне можа быць меншым у залежнасці ад магчымасцяў цягніка."
![image](https://github.com/SampleText2k77/nr-local-bel/assets/113188577/206f79b4-ca9f-43ec-b942-367f073eef58)
например здесь, в инструкции

2023-05-24 08:05 UTC, RedRibbon297 commented on game.po
> +msgstr "Верхняя мяжа тармазнога намагання цягніка. Фактычнае намаганне можа быць меншым у залежнасці ад магчымасцяў цягніка."
см. комментарий выше (строка  кода 69)

2023-05-24 08:18 UTC, RedRibbon297 commented on game.po
> +msgstr "Верхняя мяжа тармазнога намагання цягніка. Фактычнае намаганне можа быць меншым у залежнасці ад магчымасцяў цягніка."
может в зависимости не от "магчымасцi", а от "характарыстык". 
Вот есть пример из Яндекс.Переводчика для слова "capabilities":
Your shoe seems to have the ballistic capabilities of a .38 revolver.
Похоже, ваши туфли обладают баллистическими характеристиками револьвера 38 калибра.

2023-05-24 08:22 UTC, RedRibbon297 commented on game.po
> +msgstr "Верхняя мяжа цягавага намагання цягніка. Фактычнае намаганне можа быць меншым у залежнасці ад магчымасцяў цягніка."
train acceleration - это же ускорение поезда, а не тяговое усилие. 
"Верхняя мяжа _паскарэння цягніка_. Фактычнае намаганне можа быць меншым у залежнасці ад _цягавага намагання цягніка_."

2023-05-24 08:31 UTC, RedRibbon297 commented on game.po
> +msgstr "Сігналы аднабокавага руху ў тупіках платформ ігнаруюцца"
может "аднабокага" или "аднабакавога"?

2023-05-24 08:51 UTC, RedRibbon297 commented on game.po
> +msgstr "Капіраваць з новымі модамі, каб імпартаваць новыя віды аб'ектаў і ўключыць іх моды ў вашай гульні. Вам спатрэбіцца падпісацца на гэтыя моды ў Майстэрні Steam, калі вы яшчэ не зрабілі гэтага."
Предлагаю в конце изменить порядок  слов на: "калі вы яшчэ гэтага не зрабілі"
На русском на официальных крупных сайтах чаще употребляется именно так:
![2Без имени](https://github.com/SampleText2k77/nr-local-bel/assets/113188577/cbfa2f48-4148-46ae-b526-6bb6eab9a1d7)

2023-05-24 09:03 UTC, RedRibbon297 commented on game.po
> +msgstr "Перацягніце кантрольную кропку будынка, каб змяніць памер або павярнуць будынак"
"... або перавярнуць яго" ?

2023-05-24 09:06 UTC, RedRibbon297 commented on game.po
> +msgstr "Ваш ПК або маршрутызатар павінен маць прамое злучэнне з інтэрнэтам і публічны IP-адрас. Вам таксама трэба перанакіраваць UDP-порт {} у маршрутызатары на ваш ПК і дазволіць злучэнні ў міжсетка
"павiнен мець.."

2023-05-24 09:11 UTC, RedRibbon297 commented on game.po
> +msgstr "Ваш ПК або маршрутызатар павінен маць прамое злучэнне з інтэрнэтам і публічны IP-адрас. Вам таксама трэба перанакіраваць UDP-порт {} у маршрутызатары на ваш ПК і дазволіць злучэнні ў міжсетка
"Гэта функцыя не будзе працаваць ..."- может лучше не "працаваць" , а "дзейнічаць"?
"працаваць" больше про работу в смысле профессии (работать по найму, работать над проектом, в магазине)

2023-05-24 09:12 UTC, RedRibbon297 commented on game.po
> +msgstr "Ваш ПК або маршрутызатар павінен маць прамое злучэнне з інтэрнэтам і публічны IP-адрас. Вам таксама трэба перанакіраваць UDP-порт {} у маршрутызатары на ваш ПК і дазволіць злучэнні ў міжсетка
Weird and Wry - это так и надо оставить, или не придумал перевод?

2023-05-24 09:15 UTC, RedRibbon297 commented on game.po
> +msgstr "Кліенты будуць спрабаваць злучацца з вашым ПК напрамую па вашаму публічнаму IP-адрасу.\nПры наяўнасці дастатковай паласы прапускання гэта дазволіць арганізоўваць гульні з вялікай колькасцю ск
Может "дастатковай паласы прапускання" заменить как дастатковай прапускная здольнасць"?

2023-05-24 09:18 UTC, RedRibbon297 commented on game.po
> +msgstr "Кліенты будуць спрабаваць злучацца з вашым ПК напрамую па вашаму публічнаму IP-адрасу.\nПры наяўнасці дастатковай паласы прапускання гэта дазволіць арганізоўваць гульні з вялікай колькасцю ск
Может заменить "гэта дазволіць арганізоўваць гульні" на "гэта дазволіць арганізаваць гульнi" ?

2023-05-24 09:22 UTC, RedRibbon297 commented on game.po
> +msgstr "Кліенты будуць спрабаваць злучацца з вашым ПК напрамую па вашаму публічнаму IP-адрасу.\nПры наяўнасці дастатковай паласы прапускання гэта дазволіць арганізоўваць гульні з вялікай колькасцю ск
Или вообще может перефразировать вторую фразу как:
Пры наяўнасці дастатковай прапускной здольнасцi могуць быць арганізаваны гульні з вялікай колькасцю складаных аб'ектаў"

2023-05-24 09:27 UTC, RedRibbon297 commented on game.po
> +msgstr "Кліенты будуць злучацца з вашым ПК з дапамогай сеткі Steam Relay.\nЯна мае бяспечныя і аптымізаваныя CDN, хавае ваш IP-адрас, але мае абмежаваную паласу прапускання."
Надо именно "паласу прапускання", это не "прапускная здольнасць"?
Вижу уже второй раз поэтому утоняю: может это такой специальный верный перевод?

2023-05-24 09:32 UTC, RedRibbon297 commented on game.po
> +msgstr "Устаўце код далучэння, каб далучыцца да гульні, арганізаванай гульцом. Калі гулец па-за сеткай або ігнаруе ваш запыт, злучыцца не атрымаецца."
Может тут убрать "арганізаванай гульцом" ? 
Как я понимаю из контекста игры понятно, что игрок может находится в этом меню только если собирается подключится к игре с каким-то другим игроком. 
Получается перегруженное предложение с ненужным уточнением.

2023-05-24 09:35 UTC, RedRibbon297 commented on game.po
> +msgstr "Устаўце код далучэння, каб далучыцца да гульні, арганізаванай гульцом. Калі гулец па-за сеткай або ігнаруе ваш запыт, злучыцца не атрымаецца."
Я б поставила на первое место эту часть предложения: "злучыцца не атрымаецца".
То есть:
"Злучыцца не атрымаецца, калі гулец па-за сеткай або ігнаруе ваш запыт"

2023-05-24 09:39 UTC, RedRibbon297 commented on game.po
> +msgstr "Гэты код далучэння дазваляе любому гульцу далучыцца да гульні, якую вы арганізавалі, нават калі ён не ў вашых сябрах. Пераканайцеся, што правіла доступу мае значэнне «Дазволіць» або «Запытацц
Я бы поставила запятую перед "нават": "... інакш любы гулец будзе ігнараваны, нават калі ..."

2023-05-24 09:40 UTC, RedRibbon297 commented on game.po
> +msgstr "Адзін або некалькі фіксаваных прыпынкаў для адпраўлення недасяжны"
я бы перефразировала: "Для адпраўлення недасяжны адзін або некалькі фіксаваных прыпынкаў"

2023-05-24 09:51 UTC, RedRibbon297 commented on game.po
> +msgstr "Па выбары напішыце тут паведамленне, якое будзе паказана ўсім кліентам, якія далучаюцца да вашай гульні."
Может "якое будзе паказана ўсім кліентам" заменить на "якое будуць бачыць усе кліенты"?

2023-05-24 09:53 UTC, RedRibbon297 commented on game.po
> +msgstr "Па вабары ўстаўце тут спасылку, па якой кліенты змогуць перайсці ў ваш чат. Напрыклад, запрашэнне ў Discord."
"кліенты _могуць_ перайсці" ?

2023-05-24 10:00 UTC, RedRibbon297 commented on game.po
> +msgstr "Буфет"
может "вагон-ресторан", или "вагон-буфет", "вагон-салон", "вагон-люкс"

2023-05-24 10:18 UTC, RedRibbon297 requested changes

2023-05-24 10:18 UTC, RedRibbon297 commented on game.po
> +msgstr "Сістэма многіх адзінак"
Может "модульны", "сiстэма з некалькiх самастойных адзiнак"

2023-05-24 10:23 UTC, RedRibbon297 commented on game.po
> +msgstr "Уласцівасці склейвання буданкаў"
"буд**ы**нкаў"

2023-05-24 10:41 UTC, RedRibbon297 commented on game.po
> +msgstr "Даныя гэтага мода ўключаны ў бягучай гульні, але ўсталёваныя файлы патрабуюць навейшую версію гульні. Абнавіце гульню."
Предлагаю ещё немного перефразировать:
"Даныя гэтага мода ўключаны ў бягучай гульні, але ўсталёваныя файлы патрабуюць яе навейшую версію."

2023-05-24 10:48 UTC, RedRibbon297 commented on game.po
> +msgstr "Даныя гэтага мода ўключаны ў бягучай гульні, але ўсталёваныя файлы патрабуюць навейшую версію гульні. Абнавіце гульню."
Можно ещё заменить слово "патрабуецца " на "патрэбна"

2023-05-24 15:40 UTC, SampleText2k77 commented on game.po
> +msgstr "Сігналы аднабокавага руху ў тупіках платформ ігнаруюцца"
`Аднабокі` -> `Однобокий`
`Аднабаковы` -> `Односторонний`

2023-05-24 15:41 UTC, SampleText2k77 commented on game.po
> +msgstr "Перацягніце кантрольную кропку будынка, каб змяніць памер або павярнуць будынак"
`Rotate` -> `Павярнуць/варочаць`, `Flip` -> `Перавярнуць`

2023-05-24 15:44 UTC, SampleText2k77 commented on game.po
> +msgstr "Ваш ПК або маршрутызатар павінен маць прамое злучэнне з інтэрнэтам і публічны IP-адрас. Вам таксама трэба перанакіраваць UDP-порт {} у маршрутызатары на ваш ПК і дазволіць злучэнні ў міжсетка
> Weird and Wry - это так и надо оставить, или не придумал перевод?

Weird and Wry - гэта псеўданім аўтара NIMBY Rails. Яго не трэба перакладаць

2023-05-24 16:03 UTC, RedRibbon297 commented on game.po
> +msgstr "Перацягніце кантрольную кропку будынка, каб змяніць памер або павярнуць будынак"
Тут ошиблась немного. Я имела в виду в конце слово "будынак" заменить на "Яго".
Слово "перавярнуць" написала случайно, описка. 
К "павярнуць" вопросов не было.

2023-05-24 16:04 UTC, RedRibbon297 commented on game.po
> +msgstr "Ваш ПК або маршрутызатар павінен маць прамое злучэнне з інтэрнэтам і публічны IP-адрас. Вам таксама трэба перанакіраваць UDP-порт {} у маршрутызатары на ваш ПК і дазволіць злучэнні ў міжсетка
Про Weird and Why теперь буду знать.

2023-05-25 21:24 UTC, SampleText2k77 commented on game.po
> +msgstr "Па вабары ўстаўце тут спасылку, па якой кліенты змогуць перайсці ў ваш чат. Напрыклад, запрашэнне ў Discord."
`па выбары`

2023-05-30 16:43 UTC, SampleText2k77 commented on game.po
> +msgstr "Адзін або некалькі фіксаваных прыпынкаў для адпраўлення недасяжны"
Абодва варыятна прыдатны. Лепш пакіну больш блізкі да арыгінала

2023-05-30 16:47 UTC, SampleText2k77 commented on game.po
> +msgstr "Устаўце код далучэння, каб далучыцца да шматкарыстальніцкай гульні. Далучыцца не атрымаецца, калі хост па-за сеткай або ігнаруе ваш запыт."
`Злучыцца не атрымаецца`

2023-05-30 16:48 UTC, SampleText2k77 commented on game.po
> +msgstr "Фармат: гг:хх:сс\nКалі працягласць лініі карацей за гэту колькасць, да прыпынкаў з уключанай карыстальніцкай працягласцю чакання будзе дадавацца час чакання, пакуль працягласць лініі не супад
`не мае ўключанай`

2023-05-30 16:50 UTC, SampleText2k77 commented on game.po
> +msgstr "Фармат: (гг:)хх:сс\nГэты карыстальніцкі час будзе прыблізна вылічаны з улікам крэйсерскай хуткасці.\nЁн будзе праігнараваны, калі выяўленая хуткасць будзе занадта павольнай або хуткай.\nЦягні
`калі выяўленая хуткасць будзе занадта нізкай або высокай`
Нельга сказаць `хуткая хуткасць` :)

2023-05-30 16:53 UTC, SampleText2k77 commented on game.po
> +msgstr "Фармат: (гг:)хх:сс\nГэты карыстальніцкі час будзе прыблізна вылічаны з улікам крэйсерскай хуткасці.\nЁн будзе праігнараваны, калі выяўленая хуткасць будзе занадта павольнай або хуткай.\nЦягні
`Гэты карыстальніцкі час будзе апраксіміраваны шляхам знаходжання крэйсерскай хуткасці`
Інакш страчваецца арыгінальны сэнс

2023-05-30 16:56 UTC, SampleText2k77 commented on game.po
> +msgstr "Па выбары ўстаўце тут спасылку, па якой кліенты змогуць перайсці ў ваш чат. Напрыклад, запрашэнне ў Discord."
Можна апошні сказ у дужкі ўзяць

2023-05-30 16:58 UTC, SampleText2k77 commented on game.po
> +msgstr "Буфет"
Цэтлікі універсальныя. Яны могуць прымяняцца як для вагонаў, так і для цягнікоў і нават для поўных саставаў. Таму тут пакіну як зараз

2023-05-30 17:00 UTC, SampleText2k77 commented on game.po
> +msgstr "Даныя гэтага мода ўключаны ў бягучай гульні, але ўсталёваныя файлы патрабуюць навейшую версію гульні. Абнавіце гульню."
Першы варыянт гучыць добра. Выкарыстаю яго

2023-05-30 17:04 UTC, SampleText2k77 commented on game.po
> +# Перакладзена больш вольна, каб было аднолькава с аналагічным апісаннем для максімальнага тармажэння цягніка.
\+

2023-05-30 17:04 UTC, SampleText2k77 commented on game.po
> +msgstr "Даныя гэтага мода ўключаны ў бягучай гульні, але ўсталёваныя файлы патрабуюць навейшую версію гульні. Абнавіце гульню."
\+

2023-05-30 17:04 UTC, SampleText2k77 commented on game.po
> +msgstr "Верхняя мяжа цягавага намагання цягніка. Фактычнае намаганне можа быць меншым у залежнасці ад магчымасцяў цягніка."
\+

2023-05-30 17:04 UTC, SampleText2k77 commented on game.po
> +msgstr "Верхняя мяжа тармазнога намагання цягніка. Фактычнае намаганне можа быць меншым у залежнасці ад магчымасцяў цягніка."
\+

2023-05-30 17:04 UTC, SampleText2k77 commented on game.po
> +msgstr "Сігналы аднабокавага руху ў тупіках платформ ігнаруюцца"
\+

2023-05-30 17:04 UTC, SampleText2k77 commented on game.po
> +msgstr "Капіраваць з новымі модамі, каб імпартаваць новыя віды аб'ектаў і ўключыць іх моды ў вашай гульні. Вам спатрэбіцца падпісацца на гэтыя моды ў Майстэрні Steam, калі вы яшчэ не зрабілі гэтага."
\+

2023-05-30 17:04 UTC, SampleText2k77 commented on game.po
> +msgstr "Перацягніце кантрольную кропку будынка, каб змяніць памер або павярнуць будынак"
\+

2023-05-30 17:05 UTC, SampleText2k77 commented on game.po
> +msgstr "Ваш ПК або маршрутызатар павінен маць прамое злучэнне з інтэрнэтам і публічны IP-адрас. Вам таксама трэба перанакіраваць UDP-порт {} у маршрутызатары на ваш ПК і дазволіць злучэнні ў міжсетка
\+

2023-05-30 17:05 UTC, SampleText2k77 commented on game.po
> +msgstr "Кліенты будуць спрабаваць злучацца з вашым ПК напрамую па вашаму публічнаму IP-адрасу.\nПры наяўнасці дастатковай паласы прапускання гэта дазволіць арганізоўваць гульні з вялікай колькасцю ск
\+

2023-05-30 17:05 UTC, SampleText2k77 commented on game.po
> +msgstr "Кліенты будуць злучацца з вашым ПК з дапамогай сеткі Steam Relay.\nЯна мае бяспечныя і аптымізаваныя CDN, хавае ваш IP-адрас, але мае абмежаваную паласу прапускання."
\+

2023-05-30 17:05 UTC, SampleText2k77 commented on game.po
> +msgstr "Устаўце код далучэння, каб далучыцца да гульні, арганізаванай гульцом. Калі гулец па-за сеткай або ігнаруе ваш запыт, злучыцца не атрымаецца."
\+

2023-05-30 17:06 UTC, SampleText2k77 commented on game.po
> +msgstr "Гэты код далучэння дазваляе любому гульцу далучыцца да гульні, якую вы арганізавалі, нават калі ён не ў вашых сябрах. Пераканайцеся, што правіла доступу мае значэнне «Дазволіць» або «Запытацц
\+

2023-05-30 17:07 UTC, SampleText2k77 commented on game.po
> +msgstr "Гэты код далучэння дазваляе любому гульцу далучыцца да гульні, якую вы арганізавалі, нават калі ён не ў вашых сябрах. Пераканайцеся, што правіла доступу мае значэнне «Дазволіць» або «Запытацц
`будзе (што зроблены?) праігнараваны`

2023-05-30 17:07 UTC, SampleText2k77 commented on game.po
> +msgstr "Адзін або некалькі фіксаваных прыпынкаў для адпраўлення недасяжны"
\+

2023-05-30 17:07 UTC, SampleText2k77 commented on game.po
> +msgstr "Па выбары напішыце тут паведамленне, якое будзе паказана ўсім кліентам, якія далучаюцца да вашай гульні."
\+

2023-05-30 17:07 UTC, SampleText2k77 commented on game.po
> +msgstr "Па вабары ўстаўце тут спасылку, па якой кліенты змогуць перайсці ў ваш чат. Напрыклад, запрашэнне ў Discord."
\+

2023-05-30 17:08 UTC, SampleText2k77 commented on game.po
> +msgstr "Буфет"
\+

2023-05-30 17:08 UTC, SampleText2k77 commented on game.po
> +msgstr "Уласцівасці склейвання буданкаў"
\+

2023-05-30 17:08 UTC, SampleText2k77 commented on game.po
> +msgstr "Устаўце код далучэння, каб далучыцца да шматкарыстальніцкай гульні. Далучыцца не атрымаецца, калі хост па-за сеткай або ігнаруе ваш запыт."
\+

2023-05-30 17:08 UTC, SampleText2k77 commented on game.po
> +msgstr "Фармат: гг:хх:сс\nКалі працягласць лініі карацей за гэту колькасць, да прыпынкаў з уключанай карыстальніцкай працягласцю чакання будзе дадавацца час чакання, пакуль працягласць лініі не супад
\+

2023-05-30 17:08 UTC, SampleText2k77 commented on game.po
> +msgstr "Фармат: (гг:)хх:сс\nГэты карыстальніцкі час будзе прыблізна вылічаны з улікам крэйсерскай хуткасці.\nЁн будзе праігнараваны, калі выяўленая хуткасць будзе занадта павольнай або хуткай.\nЦягні
\+

2023-05-30 17:08 UTC, SampleText2k77 commented on game.po
> +msgstr "Па выбары ўстаўце тут спасылку, па якой кліенты змогуць перайсці ў ваш чат. Напрыклад, запрашэнне ў Discord."
\+

2023-05-30 17:09 UTC, SampleText2k77 commented on game.po
> +msgstr "Гэты код далучэння дазваляе любому гульцу далучыцца да гульні, якую вы арганізавалі, нават калі ён не ў вашых сябрах. Пераканайцеся, што правіла доступу мае значэнне «Дазволіць» або «Запытацц
\+

2023-05-30 17:11 UTC, SampleText2k77 commented on game.po
> +msgstr "Час, рух цягнікоў і сімуляцыя пасажыраў асобная для кожнага кліента.\nПуці, лініі і цягнікі рэдагуюцца сумесна.\nЛепш маштабуецца для вялікай колькасці складаных пабудоў, чым агульная сімуляц
`..., ..., ... асобныя`

2023-05-30 17:11 UTC, SampleText2k77 commented on game.po
> +msgstr "Час, рух цягнікоў і сімуляцыя пасажыраў агульная і сінхранізуецца паміж усімі кліентамі.\nПуці, лініі і цягнікі рэдагуюцца сумесна."
`..., ..., ... агульныя`

2023-05-30 17:12 UTC, SampleText2k77 commented on game.po
> +msgstr "Час, рух цягнікоў і сімуляцыя пасажыраў асобная для кожнага кліента.\nПуці, лініі і цягнікі рэдагуюцца сумесна.\nЛепш маштабуецца для вялікай колькасці складаных пабудоў, чым агульная сімуляц
\+

2023-05-30 17:12 UTC, SampleText2k77 commented on game.po
> +msgstr "Час, рух цягнікоў і сімуляцыя пасажыраў агульная і сінхранізуецца паміж усімі кліентамі.\nПуці, лініі і цягнікі рэдагуюцца сумесна."
\+

2023-05-30 17:32 UTC, SampleText2k77 commented on game.po
> +msgstr "Сістэма многіх адзінак"
Тут я зусім не ўпэўнены, што маецца на ўвазе.
З аднаго боку тут можна перакласці як `Маторвагонны` (састаў) або, мабыць, `Маторны` (цягнік, вагон).
З другога богу тут, здаецца, маецца на ўвазе `Сістэма многіх адзінак` (Multiple-unit train control).
Напэўна лепш перакласці як `Маторвагонны`, таму што канкрэтна для Multiple unit ёсць адпаведны артыкул у Wikipedia (https://en.wikipedia.org/wiki/Multiple_unit).

2023-05-30 17:33 UTC, SampleText2k77 commented on game.po
> +msgstr "Сістэма многіх адзінак"
\+

2023-05-30 17:59 UTC, SampleText2k77 commented on game.po
> +msgstr "Фармат: гг:хх:сс\nКалі працягласць лініі карацей за гэту колькасць, да прыпынкаў з уключанай карыстальніцкай працягласцю чакання будзе дадавацца час чакання, пакуль працягласць лініі не супад
`будзе размеркаваны`, каб было аднолькава ва ўсіх сказах

2023-05-30 17:59 UTC, SampleText2k77 commented on game.po
> +msgstr "Фармат: гг:хх:сс\nКалі працягласць лініі карацей за гэту колькасць, да прыпынкаў з уключанай карыстальніцкай працягласцю чакання будзе дадавацца час чакання, пакуль працягласць лініі не супад
\+

2023-05-31 06:12 UTC, RedRibbon297 commented on game.po
> +msgstr "Ваш ПК або маршрутызатар павінен мець прамое злучэнне з інтэрнэтам і публічны IP-адрас. Вам таксама трэба перанакіраваць UDP-порт {} у маршрутызатары на ваш ПК і дазволіць злучэнні ў міжсетка
Может перед "або" нужна запятая?
("...VPN-злучэнняу́, або...")

2023-05-31 06:21 UTC, RedRibbon297 commented on game.po
> +msgstr "Час, рух цягнікоў і сімуляцыя пасажыраў асобная для кожнага кліента.\nПуці, лініі і цягнікі рэдагуюцца сумесна.\nЛепш маштабуецца для вялікай колькасці складаных пабудоў, чым агульная сімуляц
Может перед "асоьныя" нужно тире? 
Параграф 167 правил: https://therules.ru/dash/

2023-05-31 06:22 UTC, RedRibbon297 commented on game.po
> +msgstr "Час, рух цягнікоў і сімуляцыя пасажыраў агульная і сінхранізуецца паміж усімі кліентамі.\nПуці, лініі і цягнікі рэдагуюцца сумесна."
См. коммент выше (о тире)

2023-05-31 06:30 UTC, RedRibbon297 commented on game.po
> +msgstr "Фармат: гг:хх:сс\nЧас сутак для першага адпраўлення першага аўтаматычнага цягніка з першага прыпынку.\nГэта налада ужываецца толькі для цягнікоў у рэжыме аўтаматычных загадаў.\nЦягнікі з ручн
"... налада у́ жываецца..."

2023-05-31 06:37 UTC, RedRibbon297 commented on game.po
> +msgstr "Фармат: гг:хх:сс\nЧас сутак для першага адпраўлення першага аўтаматычнага цягніка з першага прыпынку.\nГэта налада ужываецца толькі для цягнікоў у рэжыме аўтаматычных загадаў.\nЦягнікі з ручн
Как вариант можно заменить слово "вылічэнні" на "разліку"

2023-05-31 06:39 UTC, RedRibbon297 commented on game.po
> +msgstr "Фармат: гг:хх:сс\nЧас сутак для першага адпраўлення першага аўтаматычнага цягніка з першага прыпынку.\nГэта налада ужываецца толькі для цягнікоў у рэжыме аўтаматычных загадаў.\nЦягнікі з ручн
Чтобы не было рядом таких похожих слов как "улічвацца" и "вылічэнні"

2023-05-31 06:48 UTC, RedRibbon297 commented on game.po
> +msgstr "Фармат: гг:хх:сс\nЧас сутак для першага адпраўлення першага аўтаматычнага цягніка з першага прыпынку.\nГэта налада ужываецца толькі для цягнікоў у рэжыме аўтаматычных загадаў.\nЦягнікі з ручн
Может так " ... i не у́лічваюцца пры вылічэнні (разліку) інтэрвалу"?

2023-05-31 06:57 UTC, RedRibbon297 commented on game.po
> +msgstr "Фармат: (гг:)хх:сс\nГэты карыстальніцкі час будзе прыблізна вылічаны з улікам крэйсерскай хуткасці.\nЁн будзе праігнараваны, калі выяўленая хуткасць будзе занадта павольнай або хуткай.\nЦягні
"...гэту ю хуткасць"?

2023-05-31 07:33 UTC, SampleText2k77 commented on game.po
> +msgstr "Час, рух цягнікоў і сімуляцыя пасажыраў асобная для кожнага кліента.\nПуці, лініі і цягнікі рэдагуюцца сумесна.\nЛепш маштабуецца для вялікай колькасці складаных пабудоў, чым агульная сімуляц
Працяжнік патрэбны, калі сказ быў бы складзены такім чынам (у адпаведнасці з правілам): `Час, рух цягнікоў, сімуляцыя пасажыраў - УСЕ яны асобныя для кожнага кліента`

2023-05-31 07:41 UTC, SampleText2k77 commented on game.po
> +msgstr "Фармат: гг:хх:сс\nЧас сутак для першага адпраўлення першага аўтаматычнага цягніка з першага прыпынку.\nГэта налада ужываецца толькі для цягнікоў у рэжыме аўтаматычных загадаў.\nЦягнікі з ручн
\+

2023-05-31 07:53 UTC, merged